IMAGE_CODE_VALIDITY = 120

HOME_PAGE_MAX_HOUSES = 4
HOME_PAGE_DATA_REDIS_EXPIRE_SECOND = 3600

REDIS_HOUSE_INFO_EXPIRES_SECONDES = 3600

SMS_CODE_EXPIRES_SECONDS = 300

REDIS_AREA_INFO_EXPIRES_SECONDES = 86400

REDIS_HOUSE_LIST_EXPIRES_SECONDS = 86400
HOUSE_LIST_PAGE_CAPACITY = 2
HOUSE_LIST_PAGE_CACHE_NUM = 2
QINIU_URL_PREFIX = 'http://q67g039lo.bkt.clouddn.com/'
